export const FETCH_RESTAURANT = "FETCH_RESTAURANT";
export const FETCH_MENU = "FETCH_MENU";
export const SEARCH_RESTAURANT = "SEARCH_RESTAURANT";
export const FETCH_SUGGESTIONS = "FETCH_SUGGESTIONS";
